added proper ip checks to l2tunnel, quality of life changes to networ…
benjaminbaker-dev/mitmhub pull request #4
Opened 2020-03-18 18:00 UTC by jfeiglin

…k headers. Added the disruption rules interface to the l2tunnel, and a file of disruption rules

2020-03-18 19:37 UTC, benjaminbaker-dev requested changes
looks super super cool :)

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +    :return:
looks like you forgot docstr

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +def redirect_ips(target_ip, redirect_ip):
make name more indicative - i.e ip_redirect_func_factory

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +            return ip_header, ip_payload
maybe raise Exception ?

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +        if ip_header.proto == IPPROTO_TCP:
thought we dont support TCP ?

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +def change_dns_responses(domain_name, new_ip):
make func name indicative of the fact that it is a factory function

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +            return udp_header, udp_payload
raise Exception

2020-03-18 19:37 UTC, benjaminbaker-dev commented on disruption_rules.py
> +        answers = record.rr
what is qr and what is rr

2020-03-18 19:37 UTC, benjaminbaker-dev commented on tunneler/network_headers.py
> +    return struct.unpack("<H", struct.pack(">H", a))[0]
big yeet

2020-03-18 19:37 UTC, benjaminbaker-dev commented on tunneler/network_headers.py
>          return type(self).get_str_from_mac_bytes(self.src_addr)
catch attribute error maybe and raise custom ?

2020-03-18 19:37 UTC, benjaminbaker-dev commented on tunneler/tunneler.py
> +        recv_ipheader, l3_payload = self._disruption_rules[3](recv_ipheader, l3_payload)
make functions for each called _handle_ether_header and _handle_ip_header

2020-03-18 19:37 UTC, benjaminbaker-dev commented on tunneler/tunneler.py
> +            )
take recv_ip_header as parameter to generate_pseudo_header - much better than duplicated unpacking going in now

2020-03-18 19:42 UTC, benjaminbaker-dev commented
PRIVATE OBJECTS/FUNCTIONS

2020-03-19 09:18 UTC, jfeiglin commented on disruption_rules.py
> +            return ip_header, ip_payload
No you actual idiot can you not read :p... This is called on every packet that we receive, so throwing an exception is essentially dropping the packet and crashing the tunnel

2020-03-19 09:19 UTC, jfeiglin commented on disruption_rules.py
> +        if ip_header.proto == IPPROTO_TCP:
If you would read the new network headers, you might find that we do

2020-03-19 11:40 UTC, benjaminbaker-dev approved these changes

2020-03-19 11:42 UTC, merged